# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 1.0.0
  - nightly

os:
  - linux

matrix:
 allow_failures:
 - julia: nightly

notifications:
  email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.build(); Pkg.test()'

after_success:
